# Generated by Django 3.2.15 on 2022-08-30 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_guests', models.IntegerField()),
                ('booking_time', models.DateTimeField()),
                ('guest_email', models.EmailField(max_length=254)),
                ('allergies', models.TextField(max_length=200)),
                ('number_of_tables', models.IntegerField()),
                ('guest_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
