# Generated by Django 3.2.15 on 2022-09-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('booking_week', 'booking_day', 'booking_time')},
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_week',
            field=models.IntegerField(default=1, verbose_name=52),
        ),
    ]
