# Generated by Django 3.2.15 on 2022-09-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_day', models.IntegerField(choices=[(0, 'Tuesday'), (1, 'Wednesday'), (2, 'Thursday'), (3, 'Friday'), (4, 'Saturday')], default=0)),
                ('booking_time', models.IntegerField(choices=[(0, '17.00-18.30'), (1, '18.30-20.00'), (2, '20.00-21.30')], default=0)),
                ('number_of_guests', models.IntegerField(choices=[(0, 'One guest'), (1, 'Two guests'), (2, 'Three guests'), (3, 'Four guests'), (4, 'Five guests'), (5, 'Six guests'), (6, 'Seven guests'), (7, 'Eight guests')], default=0)),
                ('guest', models.TextField(blank=True, max_length=50, verbose_name='Guest')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('allergies', models.TextField(blank=True, max_length=100, verbose_name='Allergies')),
            ],
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
