# Generated by Django 3.2.15 on 2022-09-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('booking_week', 'booking_day', 'booking_time')},
        ),
    ]
