# Generated by Django 3.2.15 on 2022-09-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220908_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterModelTable(
            name='guest',
            table=None,
        ),
    ]
