# Generated by Django 3.2.15 on 2022-08-31 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220831_0521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Booking ID'),
        ),
        migrations.AddField(
            model_name='booking',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 14, 10, 0, 2361, tzinfo=utc), verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Until'),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=250, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_period',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Time period'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='allergies',
            field=models.TextField(blank=True, max_length=100, verbose_name='allergies'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
