# Generated by Django 3.2.15 on 2022-09-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20220831_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_until',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_period',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(max_length=50),
        ),
    ]
