# Generated by Django 3.2.15 on 2022-09-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20220901_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='booking_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
