# Generated by Django 3.2.15 on 2022-09-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20220901_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
